### ISSUE TITLE
An importerror  occurred when i import httplibrary

### ISSUE THREAD

**Issue by jinlxz** [peritus/robotframework-httplibrary#32]
i am a newer to this httplibrary, i have installed httplibrary 0.4.2 successfully, but a error occurred when I was importing this library, i don't know what's the issues, it says "no module named http", i don't know which file imports this module, i have checked the source code and found nothing, can anyone give me some help, thanks. (sorry maybe this is not a good place to ask for help.) 

windows xp sp3 / python 2.7.8 / httplibrary 0.4.2 / robotframework==2.8.6
 the error messages are the following.

> > > import HttpLibrary.HTTP
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named HTTP

and some verbose information are 
import jsonpointer # precompiled from C:\Python27\lib\site-packages\jsonpointer.pyc
# C:\Python27\lib\site-packages\jsonpatch.pyc matches C:\Python27\lib\site-packages\jsonpatch.py

import jsonpatch # precompiled from C:\Python27\lib\site-packages\jsonpatch.pyc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named HTTP

**Comment by jinlxz** [comment]
i got it, this error doesn't influence running tests.
