### ISSUE TITLE
import httplibrary3 failing on python3.6

### ISSUE THREAD

**Issue by Klee666** [peritus/robotframework-httplibrary#59]
Importing test library 'httplibrary3' failed: ModuleNotFoundError: No module named 'httplibrary3'
Traceback (most recent call last):
  File "e:\python36\lib\site-packages\robotide\lib\robot\utils\importer.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
PYTHONPATH:
  E:\Python36\Scripts
  E:\Python36\Lib
  E:\Python36\DLLs
  E:\Python36\Scripts
  E:\Python36
  e:\python36\python36.zip
  e:\python36\lib\site-packages
  e:\python36\lib\site-packages\robotframework_selenium2library-3.0.0-py3.6.egg
  e:\python36\lib\site-packages\win32
  e:\python36\lib\site-packages\win32\lib
  e:\python36\lib\site-packages\Pythonwin
  e:\python36\lib\site-packages\robotide\spec
  e:\python36\lib\site-packages\robotide\lib
  e:\python36\lib\site-packages\robotide\contrib\testrunner\../../lib
  e:\python36\lib\site-packages\robotide\contrib\testrunner\../../lib
  File "e:\python36\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "e:\python36\lib\site-packages\robotide\spec\libraryfetcher.py", line 24, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "e:\python36\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 50, in TestLibrary
    return_source=True)
  File "e:\python36\lib\site-packages\robotide\lib\robot\utils\importer.py", line 72, in import_class_or_module
    self._raise_import_failed(name, err)
  File "e:\python36\lib\site-packages\robotide\lib\robot\utils\importer.py", line 109, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by theddaywork** [comment]
I am getting similar errors using Robot Framework 3.1.2 and Python 3.7.1:

C:\Work\robot-scripts>robot -d results Tests\test-http.robot
[ ERROR ] Error in file 'C:\Work\robot-scripts\playground\Tests\test-http.robot': Importing test library 'HttpLibrary.HTTP' failed: ModuleNotFoundError: No module named 'httplib'
Traceback (most recent call last):
  File "c:\users\dday\appdata\local\programs\python\python37\lib\site-packages\HttpLibrary\__init__.py", line 7, in <module>
    from HttpLibrary import livetest
  File "c:\users\dday\appdata\local\programs\python\python37\lib\site-packages\HttpLibrary\livetest.py", line 43, in <module>
    import httplib
C:\Work\robot-scripts>robot --version
Robot Framework 3.1.2 (Python 3.7.1 on win32)
